--ASSIGNMENT 11

--Q1
CREATE PROCEDURE SP_CustomersInCity @CNAME varchar(100)
AS
BEGIN
	SELECT DISTINCT D.CNAME FROM CUSTOMER C
	JOIN DEPOSIT D
	ON C.CNAME = D.CNAME
	JOIN BRANCH B
	ON C.CITY = B.CITY
	WHERE D.BNAME IN (SELECT BNAME FROM BRANCH WHERE BRANCH.CITY IN (SELECT CITY FROM CUSTOMER WHERE CNAME = @CNAME))
END

EXEC SP_CustomersInCity 'NAREN'


--Q3

CREATE PROCEDURE SP_CityWiseCustomers @City VARCHAR(100)
AS
BEGIN
	SELECT COUNT(CNAME) AS CustomerCount FROM CUSTOMER
	WHERE CITY = @City
END

EXEC SP_CityWiseCustomers 'MUMBAI'



--Q4

--Q5
CREATE PROCEDURE SP_BranchCityCustomerCount @Branch varchar(100)
AS
BEGIN
	SELECT COUNT(*) FROM CUSTOMER C
	JOIN BRANCH B
	ON C.CITY = B.CITY
	WHERE B.BNAME = @Branch
END

EXEC SP_BranchCityCustomerCount 'POWAI'

--Q6

CREATE PROCEDURE SP_StoreJSONIntoDeposit @InJSON varchar(MAX)
AS
BEGIN
	
	INSERT INTO DEPOSIT
	SELECT * FROM OPENJSON(@InJSON) WITH (ActNo int, CNAME varchar(MAX),BNAME varchar(MAX),Amount int,Adate date)
	WHERE Amount>10 AND Adate = CONVERT(date,GETDATE())

END

EXEC SP_StoreJSONIntoDeposit '{"ActNo":115,"CNAME":"MADHURI", "BNAME":"AJNI", "Amount":5000, "Adate":"2022-06-30"}'


SELECT * FROM DEPOSIT
