/*String Functions*/

SELECT ASCII(FirstName) FROM Employees

SELECT CHAR(65)

SELECT CHARINDEX('N','FirstName')

SELECT CONCAT('THIS IS A' , ' CONCAT EXAMPLE')

SELECT 'TEST '+ 'STRING'

SELECT DATALENGTH(FirstName) FROM Employees

SELECT DIFFERENCE ('JAY', 'MIN')

SELECT LEFT(FirstName,2) FROM Employees

SELECT LEN(FirstName) FROM Employees

SELECT UPPER(FirstName) FROM Employees

SELECT NCHAR(65)

SELECT PATINDEX('%World%','Hello World')

SELECT REPLACE('Demo String', 'S','P')

SELECT REPLICATE('DEMO STRING',5)

SELECT REVERSE('STRING')

SELECT STR(10)

SELECT STUFF('STRING',2,3,'HELLO')

SELECT SUBSTRING('Hello World', 2,7)

SELECT COALESCE(NULL,NULL, 'Hello WOrld', NULL)