-- Isolation Level example.

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED

BEGIN TRANSACTION ChangeEmail
BEGIN TRY
UPDATE Person.EmailAddress
SET EmailAddress= 'MICHAEL@YAHOO.COM'
WHERE BusinessEntityID=6
UPDATE Person.BusinessEntityAddress
SET AddressID=328
WHERE BusinessEntityID=1
COMMIT TRANSACTION TR1
SELECT 'TRANSACTION EXECUTED'
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION TR1
SELECT 'TRANSACTION ROLLBACK'
END CATCH