
CREATE VIEW vwDeptManagerCity
AS
SELECT DISTINCT(d.DEPARTMENT_NAME), e1.FIRST_NAME AS ManagerName,l.CITY FROM employees e
JOIN departments d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN employees e1 ON e.MANAGER_ID = e1.EMPLOYEE_ID
JOIN locations l ON d.LOCATION_ID = l.LOCATION_ID
WHERE e.MANAGER_ID = e1.EMPLOYEE_ID

SELECT * FROM vwDeptManagerCity

SELECT d.DEPARTMENT_NAME, (e.FIRST_NAME+ '' + e.LAST_NAME) AS ManagerName,e.HIRE_DATE, e.SALARY FROM employees e
JOIN departments d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE DATEDIFF(YEAR,e.HIRE_DATE, GETDATE())>15

