/*Assignment 5*/

SELECT DATEDIFF(DAY,EMPLOYEE.Joining_Date,INCENTIVE.INCENTIVE_DATE) FROM EMPLOYEE
RIGHT JOIN INCENTIVE
ON EMPLOYEE.Employee_ID = INCENTIVE.Employee_Ref_ID

SELECT First_Name, INCENTIVE_AMOUNT FROM EMPLOYEE
RIGHT JOIN INCENTIVE
ON EMPLOYEE.Employee_ID = INCENTIVE.Employee_Ref_ID
WHERE INCENTIVE_AMOUNT>3000

SELECT First_Name,INCENTIVE_AMOUNT FROM EMPLOYEE
LEFT JOIN INCENTIVE
ON EMPLOYEE.Employee_ID = INCENTIVE.Employee_Ref_ID

SELECT First_Name,Last_Name, MANAGERNAME FROM EMPLOYEE

SELECT Employee_ID ,COALESCE (Incentive_Amount,0) 
FROM Employee LEFT JOIN Incentive 
ON Employee.Employee_ID = Incentive.Employee_Ref_ID

